### PR TITLE
Upgrade dependencies (e.g. FitNesse)

### PR DESCRIPTION
**Pull request by raboof**
This branch currently fails to integration-test, so that needs to be fixed before we merge.

### CODE REVIEW

**Comment by raboof** [comment]
```
[java] Executing command: ProjectXebium?suite&format=text&excludeSuiteFilter=NotOnPhantomJS
     [java] -----Command Output-----
     [java] Exception in thread "main" java.lang.AbstractMethodError
     [java] 	at fitnesse.wikitext.parser.ParseSpecification.parse(ParseSpecification.java:96)
     [java] 	at fitnesse.wikitext.parser.Parser.parse(Parser.java:141)
     [java] 	at fitnesse.wikitext.parser.Parser.parse(Parser.java:137)
     [java] 	at fitnesse.wikitext.parser.Parser.parseTo(Parser.java:112)
     [java] 	at fitnesse.wikitext.parser.Parser.parseTo(Parser.java:108)
     [java] 	at fitnesse.wikitext.parser.Collapsible.parse(Collapsible.java:35)
     [java] 	at fitnesse.wikitext.parser.ParseSpecification.parse(ParseSpecification.java:96)
```

**Comment by raboof** [comment]
The compiler error is fixed (was due to an older version of the maven classpath plugin).

Now one of the integration-tests still fails. Tricky thing is it seems to work fine when ran from the browser :(

**Comment by raboof** [comment]
A change in FitNesse causes the FitNesse HTTP server not to be started when you run a specific command - like we do in 'mvn integration-test'. 

That is desirable and makes total sense, but in our case it currently causes problems because we use the 'currently running' FitNesse instance itself as the SUT for the integration tests. 

I think it would be a good idea to make our own `pom.xml` a more typical example of how you'd invoke FitNesse from maven: first starting the SUT, then running the tests, then reporting on the results.

**Comment by amolenaar** [comment]
Disabling the maven class path plugin makes the pages render again. I think we have to look for a solution there.

**Comment by amolenaar** [comment]
Whoops. I had to catch up.

**Comment by amolenaar** [comment]
Shouldn't we just start FitNesse from FitNesse (on a different port). That would make more sense IMHO.

**Comment by raboof** [comment]
Yes! Setting it up like a more traditional SUT :). Would be nice to still have it 'test itself' when running interactively though.

**Comment by raboof** [comment]
I updated our integrationtests to start the SUT from the tests.

As I made a fixture for starting FitNesse, the project now has a compile-time dependency on FitNesse rather than run-time. That seems to make sense to me, anyway - but perhaps I'm missing something?

**Comment by raboof** [comment]
To be quite honest I think starting the SUT from your Xebium test is an anti-pattern and we're setting a bad example here - rewriting things so we can start the SUT 'separately' is not entirely trivial though, so this'll have to do for now.

**Comment by raboof** [comment]
Not sure why the FailFast test is still failing when run as part of the suite (it now seems OK when being run separately). Help welcome :)

**Comment by raboof** [comment]
@amolenaar @denniebouman does either of you have time to give the PR a review and/or test? Much appreciated!

**Comment by raboof** [comment]
@mjvdende perhaps?

**Comment by raboof** [comment]
Got some reports back that this version is working well, so merging

**Pull request merged**
