### PR TITLE
Declare maintenance mode

### PR DESCRIPTION
**Pull request by raboof**
Should we recommend against picking up Xebium for new projects? Should we recommend an alternative? @amolenaar ?

### CODE REVIEW

**Comment by raboof** [comment]
(build failure is unrelated to this PR, #154)

**Comment by cwortel** [comment]
I'd say recommend against using it in serious projects. we could provide a short list of alternatives and some references to some serious automation guidelines.

**Comment by denniebouman** [comment]
When Xebium is no longer actively maintained, Xebium will always be behind of newer versions of FitNesse and Selenium. 
So I would also recommend against picking up Xebium for new projects.

**Comment by raboof** [comment]
@cwortel what alternatives would you recommend?

@denniebouman we're still open to contributions though, upgrading generally isn't that bad (it's actually testing for regressions that's the most tricky)

**Comment by cwortel** [comment]
My recommendations:
If you have to do frontend testing my advise would be to only do the bare minimum in end to end tests. Try to test only the flows, avoid testing to much detail (this will result in a maintenance hell at some point).

There are probably still some Xebium-like alternatives around for Fitnesse, using a DSL or keyword based structure. However when used on a larger scale they will all result in poor maintenance abilities at some point (to my opinion). 

For educational purposes the approach could be beneficial. Xebium helps you to get started and understand Fitnesse, without to much hassle. 

Proper alternatives:

Fitnesse/webdriver with custom fixtures + page objects (avoid the use of scenario tables)
Protractor for Angular 
Cucumber/webdriver + page objects
Serenity
Concordion+webdriver
Robot framework

Regards,

Cirilo

**Comment by jguglielmi** [comment]
Has anyone attempted to update the dependencies for fitnesse and selenium and try on a new browser?  I last updated a few months ago.

**Comment by raboof** [comment]
@jguglielmi Well, there's https://github.com/xebia/Xebium/pull/148 - that has some newer versions but not the very latest. The reason I haven't merged those yet is that I don't feel they're sufficiently tested.

**Comment by jguglielmi** [comment]
@raboof Thanks for the update!  When I get home later today, I'll pull the request in locally and give it a shot.  The travis build is of more importance to me.

**Comment by pmularien** [comment]
@raboof it actually feels like Xebium is fairly unique in this space, certainly within the FitNesse community. Are there roadblocks to opening the project up to allow for a broader set of contributors or to allow for others to help administer it?

**Comment by raboof** [comment]
@pmularien yes, the proposed text in this PR needs a bit of a revision :). Indeed since that was written some more work has been done (i.e. https://github.com/xebia/Xebium/pull/148 was merged).

We welcome issues and PR's, and we're open to adding maintainers from outside of Xebia to the project when they have a good track record of reliable PR's.

**Comment by alexanderrosenfeldfmr** [comment]
@raboof I've submitted a PR #162 if you're still accepting changes to the project.

**Pull request merged**
